// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Booking is the predicate function for booking builders.
type Booking func(*sql.Selector)

// Operationroom is the predicate function for operationroom builders.
type Operationroom func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
