// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"
	// FieldPatientAge holds the string denoting the patient_age field in the database.
	FieldPatientAge = "patient_age"

	// EdgePatientID holds the string denoting the patient_id edge name in mutations.
	EdgePatientID = "patient_id"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// PatientIDTable is the table the holds the patient_id relation/edge.
	PatientIDTable = "bookings"
	// PatientIDInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	PatientIDInverseTable = "bookings"
	// PatientIDColumn is the table column denoting the patient_id relation/edge.
	PatientIDColumn = "patient_patient_id"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldPatientName,
	FieldPatientAge,
}

var (
	// PatientNameValidator is a validator for the "patient_name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
)
