// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/Toneone11/app/ent/booking"
	"github.com/Toneone11/app/ent/operationroom"
	"github.com/Toneone11/app/ent/patient"
	"github.com/Toneone11/app/ent/predicate"
	"github.com/Toneone11/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BookingUpdate is the builder for updating Booking entities.
type BookingUpdate struct {
	config
	hooks      []Hook
	mutation   *BookingMutation
	predicates []predicate.Booking
}

// Where adds a new predicate for the builder.
func (bu *BookingUpdate) Where(ps ...predicate.Booking) *BookingUpdate {
	bu.predicates = append(bu.predicates, ps...)
	return bu
}

// SetDate sets the date field.
func (bu *BookingUpdate) SetDate(t time.Time) *BookingUpdate {
	bu.mutation.SetDate(t)
	return bu
}

// SetDoctorIDID sets the doctor_id edge to User by id.
func (bu *BookingUpdate) SetDoctorIDID(id int) *BookingUpdate {
	bu.mutation.SetDoctorIDID(id)
	return bu
}

// SetNillableDoctorIDID sets the doctor_id edge to User by id if the given value is not nil.
func (bu *BookingUpdate) SetNillableDoctorIDID(id *int) *BookingUpdate {
	if id != nil {
		bu = bu.SetDoctorIDID(*id)
	}
	return bu
}

// SetDoctorID sets the doctor_id edge to User.
func (bu *BookingUpdate) SetDoctorID(u *User) *BookingUpdate {
	return bu.SetDoctorIDID(u.ID)
}

// SetPatientIDID sets the patient_id edge to Patient by id.
func (bu *BookingUpdate) SetPatientIDID(id int) *BookingUpdate {
	bu.mutation.SetPatientIDID(id)
	return bu
}

// SetNillablePatientIDID sets the patient_id edge to Patient by id if the given value is not nil.
func (bu *BookingUpdate) SetNillablePatientIDID(id *int) *BookingUpdate {
	if id != nil {
		bu = bu.SetPatientIDID(*id)
	}
	return bu
}

// SetPatientID sets the patient_id edge to Patient.
func (bu *BookingUpdate) SetPatientID(p *Patient) *BookingUpdate {
	return bu.SetPatientIDID(p.ID)
}

// SetOperationroomIDID sets the operationroom_id edge to Operationroom by id.
func (bu *BookingUpdate) SetOperationroomIDID(id int) *BookingUpdate {
	bu.mutation.SetOperationroomIDID(id)
	return bu
}

// SetNillableOperationroomIDID sets the operationroom_id edge to Operationroom by id if the given value is not nil.
func (bu *BookingUpdate) SetNillableOperationroomIDID(id *int) *BookingUpdate {
	if id != nil {
		bu = bu.SetOperationroomIDID(*id)
	}
	return bu
}

// SetOperationroomID sets the operationroom_id edge to Operationroom.
func (bu *BookingUpdate) SetOperationroomID(o *Operationroom) *BookingUpdate {
	return bu.SetOperationroomIDID(o.ID)
}

// Mutation returns the BookingMutation object of the builder.
func (bu *BookingUpdate) Mutation() *BookingMutation {
	return bu.mutation
}

// ClearDoctorID clears the doctor_id edge to User.
func (bu *BookingUpdate) ClearDoctorID() *BookingUpdate {
	bu.mutation.ClearDoctorID()
	return bu
}

// ClearPatientID clears the patient_id edge to Patient.
func (bu *BookingUpdate) ClearPatientID() *BookingUpdate {
	bu.mutation.ClearPatientID()
	return bu
}

// ClearOperationroomID clears the operationroom_id edge to Operationroom.
func (bu *BookingUpdate) ClearOperationroomID() *BookingUpdate {
	bu.mutation.ClearOperationroomID()
	return bu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (bu *BookingUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BookingUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BookingUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BookingUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BookingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   booking.Table,
			Columns: booking.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: booking.FieldID,
			},
		},
	}
	if ps := bu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: booking.FieldDate,
		})
	}
	if bu.mutation.DoctorIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.DoctorIDTable,
			Columns: []string{booking.DoctorIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.DoctorIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.DoctorIDTable,
			Columns: []string{booking.DoctorIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.PatientIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.PatientIDTable,
			Columns: []string{booking.PatientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.PatientIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.PatientIDTable,
			Columns: []string{booking.PatientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.OperationroomIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.OperationroomIDTable,
			Columns: []string{booking.OperationroomIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: operationroom.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.OperationroomIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.OperationroomIDTable,
			Columns: []string{booking.OperationroomIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: operationroom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{booking.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BookingUpdateOne is the builder for updating a single Booking entity.
type BookingUpdateOne struct {
	config
	hooks    []Hook
	mutation *BookingMutation
}

// SetDate sets the date field.
func (buo *BookingUpdateOne) SetDate(t time.Time) *BookingUpdateOne {
	buo.mutation.SetDate(t)
	return buo
}

// SetDoctorIDID sets the doctor_id edge to User by id.
func (buo *BookingUpdateOne) SetDoctorIDID(id int) *BookingUpdateOne {
	buo.mutation.SetDoctorIDID(id)
	return buo
}

// SetNillableDoctorIDID sets the doctor_id edge to User by id if the given value is not nil.
func (buo *BookingUpdateOne) SetNillableDoctorIDID(id *int) *BookingUpdateOne {
	if id != nil {
		buo = buo.SetDoctorIDID(*id)
	}
	return buo
}

// SetDoctorID sets the doctor_id edge to User.
func (buo *BookingUpdateOne) SetDoctorID(u *User) *BookingUpdateOne {
	return buo.SetDoctorIDID(u.ID)
}

// SetPatientIDID sets the patient_id edge to Patient by id.
func (buo *BookingUpdateOne) SetPatientIDID(id int) *BookingUpdateOne {
	buo.mutation.SetPatientIDID(id)
	return buo
}

// SetNillablePatientIDID sets the patient_id edge to Patient by id if the given value is not nil.
func (buo *BookingUpdateOne) SetNillablePatientIDID(id *int) *BookingUpdateOne {
	if id != nil {
		buo = buo.SetPatientIDID(*id)
	}
	return buo
}

// SetPatientID sets the patient_id edge to Patient.
func (buo *BookingUpdateOne) SetPatientID(p *Patient) *BookingUpdateOne {
	return buo.SetPatientIDID(p.ID)
}

// SetOperationroomIDID sets the operationroom_id edge to Operationroom by id.
func (buo *BookingUpdateOne) SetOperationroomIDID(id int) *BookingUpdateOne {
	buo.mutation.SetOperationroomIDID(id)
	return buo
}

// SetNillableOperationroomIDID sets the operationroom_id edge to Operationroom by id if the given value is not nil.
func (buo *BookingUpdateOne) SetNillableOperationroomIDID(id *int) *BookingUpdateOne {
	if id != nil {
		buo = buo.SetOperationroomIDID(*id)
	}
	return buo
}

// SetOperationroomID sets the operationroom_id edge to Operationroom.
func (buo *BookingUpdateOne) SetOperationroomID(o *Operationroom) *BookingUpdateOne {
	return buo.SetOperationroomIDID(o.ID)
}

// Mutation returns the BookingMutation object of the builder.
func (buo *BookingUpdateOne) Mutation() *BookingMutation {
	return buo.mutation
}

// ClearDoctorID clears the doctor_id edge to User.
func (buo *BookingUpdateOne) ClearDoctorID() *BookingUpdateOne {
	buo.mutation.ClearDoctorID()
	return buo
}

// ClearPatientID clears the patient_id edge to Patient.
func (buo *BookingUpdateOne) ClearPatientID() *BookingUpdateOne {
	buo.mutation.ClearPatientID()
	return buo
}

// ClearOperationroomID clears the operationroom_id edge to Operationroom.
func (buo *BookingUpdateOne) ClearOperationroomID() *BookingUpdateOne {
	buo.mutation.ClearOperationroomID()
	return buo
}

// Save executes the query and returns the updated entity.
func (buo *BookingUpdateOne) Save(ctx context.Context) (*Booking, error) {

	var (
		err  error
		node *Booking
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			mut = buo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BookingUpdateOne) SaveX(ctx context.Context) *Booking {
	b, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return b
}

// Exec executes the query on the entity.
func (buo *BookingUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BookingUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BookingUpdateOne) sqlSave(ctx context.Context) (b *Booking, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   booking.Table,
			Columns: booking.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: booking.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Booking.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := buo.mutation.Date(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: booking.FieldDate,
		})
	}
	if buo.mutation.DoctorIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.DoctorIDTable,
			Columns: []string{booking.DoctorIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.DoctorIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.DoctorIDTable,
			Columns: []string{booking.DoctorIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.PatientIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.PatientIDTable,
			Columns: []string{booking.PatientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.PatientIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.PatientIDTable,
			Columns: []string{booking.PatientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.OperationroomIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.OperationroomIDTable,
			Columns: []string{booking.OperationroomIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: operationroom.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.OperationroomIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   booking.OperationroomIDTable,
			Columns: []string{booking.OperationroomIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: operationroom.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	b = &Booking{config: buo.config}
	_spec.Assign = b.assignValues
	_spec.ScanValues = b.scanValues()
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{booking.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return b, nil
}
