/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Project API Booking
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOperationroom,
    EntOperationroomFromJSON,
    EntOperationroomFromJSONTyped,
    EntOperationroomToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBookingEdges
 */
export interface EntBookingEdges {
    /**
     * 
     * @type {EntUser}
     * @memberof EntBookingEdges
     */
    doctorID?: EntUser;
    /**
     * 
     * @type {EntOperationroom}
     * @memberof EntBookingEdges
     */
    operationroomID?: EntOperationroom;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntBookingEdges
     */
    patientID?: EntPatient;
}

export function EntBookingEdgesFromJSON(json: any): EntBookingEdges {
    return EntBookingEdgesFromJSONTyped(json, false);
}

export function EntBookingEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBookingEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctorID': !exists(json, 'DoctorID') ? undefined : EntUserFromJSON(json['DoctorID']),
        'operationroomID': !exists(json, 'OperationroomID') ? undefined : EntOperationroomFromJSON(json['OperationroomID']),
        'patientID': !exists(json, 'PatientID') ? undefined : EntPatientFromJSON(json['PatientID']),
    };
}

export function EntBookingEdgesToJSON(value?: EntBookingEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctorID': EntUserToJSON(value.doctorID),
        'operationroomID': EntOperationroomToJSON(value.operationroomID),
        'patientID': EntPatientToJSON(value.patientID),
    };
}


