/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Project API Booking
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookingEdges,
    EntBookingEdgesFromJSON,
    EntBookingEdgesFromJSONTyped,
    EntBookingEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBooking
 */
export interface EntBooking {
    /**
     * Date holds the value of the "date" field.
     * @type {string}
     * @memberof EntBooking
     */
    date?: string;
    /**
     * 
     * @type {EntBookingEdges}
     * @memberof EntBooking
     */
    edges?: EntBookingEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBooking
     */
    id?: number;
}

export function EntBookingFromJSON(json: any): EntBooking {
    return EntBookingFromJSONTyped(json, false);
}

export function EntBookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBooking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : json['date'],
        'edges': !exists(json, 'edges') ? undefined : EntBookingEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntBookingToJSON(value?: EntBooking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'edges': EntBookingEdgesToJSON(value.edges),
        'id': value.id,
    };
}


