/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Project API Booking
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOperationroomEdges,
    EntOperationroomEdgesFromJSON,
    EntOperationroomEdgesFromJSONTyped,
    EntOperationroomEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntOperationroom
 */
export interface EntOperationroom {
    /**
     * 
     * @type {EntOperationroomEdges}
     * @memberof EntOperationroom
     */
    edges?: EntOperationroomEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntOperationroom
     */
    id?: number;
    /**
     * OperationroomName holds the value of the "operationroom_name" field.
     * @type {string}
     * @memberof EntOperationroom
     */
    operationroomName?: string;
}

export function EntOperationroomFromJSON(json: any): EntOperationroom {
    return EntOperationroomFromJSONTyped(json, false);
}

export function EntOperationroomFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntOperationroom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntOperationroomEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'operationroomName': !exists(json, 'operationroom_name') ? undefined : json['operationroom_name'],
    };
}

export function EntOperationroomToJSON(value?: EntOperationroom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntOperationroomEdgesToJSON(value.edges),
        'id': value.id,
        'operationroom_name': value.operationroomName,
    };
}


