// Code generated by entc, DO NOT EDIT.

package operationroom

import (
	"github.com/Toneone11/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// OperationroomName applies equality check predicate on the "operationroom_name" field. It's identical to OperationroomNameEQ.
func OperationroomName(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameEQ applies the EQ predicate on the "operationroom_name" field.
func OperationroomNameEQ(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameNEQ applies the NEQ predicate on the "operationroom_name" field.
func OperationroomNameNEQ(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameIn applies the In predicate on the "operationroom_name" field.
func OperationroomNameIn(vs ...string) predicate.Operationroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Operationroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldOperationroomName), v...))
	})
}

// OperationroomNameNotIn applies the NotIn predicate on the "operationroom_name" field.
func OperationroomNameNotIn(vs ...string) predicate.Operationroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Operationroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldOperationroomName), v...))
	})
}

// OperationroomNameGT applies the GT predicate on the "operationroom_name" field.
func OperationroomNameGT(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameGTE applies the GTE predicate on the "operationroom_name" field.
func OperationroomNameGTE(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameLT applies the LT predicate on the "operationroom_name" field.
func OperationroomNameLT(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameLTE applies the LTE predicate on the "operationroom_name" field.
func OperationroomNameLTE(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameContains applies the Contains predicate on the "operationroom_name" field.
func OperationroomNameContains(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameHasPrefix applies the HasPrefix predicate on the "operationroom_name" field.
func OperationroomNameHasPrefix(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameHasSuffix applies the HasSuffix predicate on the "operationroom_name" field.
func OperationroomNameHasSuffix(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameEqualFold applies the EqualFold predicate on the "operationroom_name" field.
func OperationroomNameEqualFold(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldOperationroomName), v))
	})
}

// OperationroomNameContainsFold applies the ContainsFold predicate on the "operationroom_name" field.
func OperationroomNameContainsFold(v string) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldOperationroomName), v))
	})
}

// HasOperationroomID applies the HasEdge predicate on the "operationroom_id" edge.
func HasOperationroomID() predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OperationroomIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OperationroomIDTable, OperationroomIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOperationroomIDWith applies the HasEdge predicate on the "operationroom_id" edge with a given conditions (other predicates).
func HasOperationroomIDWith(preds ...predicate.Booking) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OperationroomIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OperationroomIDTable, OperationroomIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Operationroom) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Operationroom) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Operationroom) predicate.Operationroom {
	return predicate.Operationroom(func(s *sql.Selector) {
		p(s.Not())
	})
}
